WebClient/Controllers/DoctorPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class DoctorPageController : Controller
    {
        public IActionResult Index()
        {
            string active = "active";
            ViewBag.Dashboard = active;
            return View();
        }
    }
}

WebClient/Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class MedicineController : Controller
    {
        public IActionResult Index()
        {
            string active = "active";
            ViewBag.MedicineManage = active;
            return View();
        }
    }
}

WebClient/Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class PatientController : Controller
    {
        public IActionResult Index()
        {
            string active = "active";
            ViewBag.PatientManage = active;
            return View();
        }
    }
}

WebClient/Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using WebClient.Models;
using BusinessObject;
using Syncfusion.EJ2.Linq;
using System.Net.Http;
using System.Linq;
using Event = WebClient.Models.Event;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Text.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace WebClient.Controllers
{
    public partial class ScheduleController : Controller
    {
        public IActionResult Overview()
        {
            return View();
        }
    }
}

WebClient/Views/Shared/Header.cshtml
<header>
    <h2>
        <label for="nav-toggle">
            <span><i class="fa-solid fa-bars"></i></span>
        </label>
    </h2>
    <div class="user-wrapper">
        <img src="./img/user.png" width="40px" height="40px" onclick="toggleMenu()">
        <div onclick="toggleMenu()">
            <h5>Thanh Phong Vo</h5>
            <small>Doctor</small>
        </div>
        <div class="sub-menu-wrap" id="subMenu">
            <div class="sub-menu">
                <div class="user-info">
                    <img src="./img/user.png" width="20px" height="20px">
                    <p>Thanh Phong Vo<p>
                </div>
                <hr>
                <a href="" class="sub-menu-link">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <p>Logout</p>
                    <span>></span>
                </a>
            </div>
        </div>
    </div>
</header>

WebClient/Views/Shared/SideBar.cshtml
<input type="checkbox" id="nav-toggle">
<div class="sidebar">
    <div class="sidebar-brand">
        <a href=""><img src="./img/VTP2 1.svg" alt="Logo" width="100%"></a>
    </div>
    <div class="sidebar-menu" id="sidebar">
        <ul id="main-nav">
            <li class="@ViewBag.DashBoard">
                <a asp-action="Index" asp-controller="DoctorPage" class="link-active" id="dashBoard"><i class="fa-solid fa-gauge"></i><span>Dashboard</span></a>
            </li>
            <li class="@ViewBag.Scheduler">
                <a asp-action="Overview" asp-controller="Schedule" class="link-active" id="Schedule"><i class="fa-solid fa-stethoscope"></i><span>Schedule</span></a>
            </li>
            <li class="@ViewBag.MedicalExam">
                <a asp-action="Index" asp-controller="MedicalExam" class="link-active" id="medicalExam"><i class="fa-solid fa-stethoscope"></i><span>Medical Exam</span></a>
            </li>
            <li class="@ViewBag.Appointment">
                <a asp-action="Index" asp-controller="Appointment" class="link-active" id="appoitment"><i class="fa-solid fa-calendar-check"></i><span>Appointment</span></a>
            </li>
            <li class="@ViewBag.ReceivePatient">
                <a asp-action="Index" asp-controller="ReceivePatient" class="link-active" id="receivePatient"><i class="fa-solid fa-hand-holding-medical"></i><span>Recieve Patient</span></a>
            </li>
            <li class="@ViewBag.MedicineManage">
                <a asp-action="Index" asp-controller="Medicine" class="link-active" id="medicineManage"><i class="fa-solid fa-capsules"></i><span>Medicine Manage</span></a>
            </li>
            <li class="@ViewBag.PatientManage">
                <a asp-action="Index" asp-controller="Patient" class="link-active" id="patientManage"><i class="fa-solid fa-bed-pulse"></i><span>Patient Manage</span></a>
            </li>
        </ul>
    </div>
</div>

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap//dist/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebClient/Views/Shared/_LayoutDoctor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Boostrap Css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Boostrap Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Boostrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <!-- Font Awsome -->
    <script src="https://kit.fontawesome.com/d9a92be812.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Main css -->
    <link rel="stylesheet" href="./css/dashboard.css">
    <!-- DataTable -->
    <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />

    <title>Admin Page</title>
</head>
<body>
    @await Html.PartialAsync("SideBar.cshtml")
    <div class="main-content">
        @await Html.PartialAsync("Header.cshtml")
        <main>
            @RenderBody()
            @*@RenderSection("Scripts", required: false)*@
            @await RenderSectionAsync("Scripts", false)
        </main>
    </div>

    <script>
        let subMenu = document.getElementById("subMenu");
        function toggleMenu() {
            subMenu.classList.toggle("open-menu");
        }
    </script>
        <script src="~/lib/jquery/dist/jquery.js"></script>

        <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
        <script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>

</body>
</html>

WebClient/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- main css -->
    <link rel="stylesheet" href="./css/homecss.css" />
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Exo:wght@400;600&display=swap"
          rel="stylesheet" />
    <link rel="shortcut icon" href="./img/VTP2 1.svg" />  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <title>EGO Clinic</title>
</head>
<body>
    <!-- header -->
    <header>
        <div class="container">
            <nav class="navbar">
                <!-- logo -->
                <ul class="navbar__links">
                    <div class="navbar__logo">
                        <img src="./img/VTP2 1.svg" alt="website logo" />
                    </div>
                </ul>

                <!-- links -->
                <ul class="navbar__links">
                    <li class="navbar__link"><a href="#" class="">Home</a></li>
                    <li class="navbar__link"><a href="#">About</a></li>
                    <li class="navbar__link"><a href="#">Make Appointment</a></li>
                </ul>

                <ul class="navbar__links">
                    <li class="navbar__link"><a href="#" id="signIn">Sign in</a></li>
                    <a href="#"><button class="navbar__btn" id="Register">Register</button></a>
                </ul>
            </nav>
        </div>
    </header>
    <!-- body-form -->
    <div class="form-left">
        <h1>Sign up to track your health</h1>
        <p>
            if you have ready an account you can
            <a href="#" class="Login-text" target="_blank">Login </a>here
        </p>
        <div class="text-span"></div>
    </div>

    <div class="form-center">
        <img src="./img/3636112-removebg-preview 1.png"
             alt=""
             class="img-form-center" />
    </div>
    <!-- form-right -->
    
    <div class="container" id="container">
        <form class="form-right-login" id="loginForm">
          <h2>Welcome User</h2>
          <input type="email" placeholder="Email" />
          <input type="password" placeholder="Password" />
          <a href="#">Forgot your password?</a>
          <button class="confrim">Sign In</button>
        </form> 
        <form class="form-right-register" id="registerForm">
            <h2>Register for more</h2>
            <input type="text" placeholder="Username" />
            <input type="email" placeholder="Email" />
            <input type="password" placeholder="Password" />
            <input type="password" placeholder="Confirm Password" />
            <a href="#">Forgot your password?</a>
            <button class="confrim">Register  </button>
        </form>
    </div>
    <script src="https://kit.fontawesome.com/d9a92be812.js"
            crossorigin="anonymous"></script>
    <script src="./js/home.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderBody()
</body>
</html>